import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  projectSidebar: [
    "bikes/w2025-bakfiets",
    "W2025-projects/electric_skateboard_2025",
    "W2025-projects/onewheel_2025",
    "bikes/w2025-longtail-conversion-kit",
    "W2025-projects/gokart_2025",
    "W2025-projects/custom_remote_control_2025",
    "W2025-projects/electrium_shop_2025",
    "W2025-projects/scooter_2024",
    "bikes/w2025-road-bike",
    "W2025-projects/electric_couch_2024",
    {
      type: "category",
      label: "Fall 2025 Projects",
      collapsed: false,
      items: [
        "bikes/f2025-ebike",
        "F2025-projects/F25 Skateboard",
        "F2025-projects/f25_auto_pr_bot",
        "bikes/f2025-mid-bike-conversion-kit",
        "F2025-projects/f25_request_platform",
        "F2025-projects/portable_media_player_f2025",
        "F2025-projects/f25_meeting_note_bot",
        "F2025-projects/f25_smart_qa_bot",
        "F2025-projects/f25_electrium_shop",
      ],
    },
    {
      type: "category",
      label: "2023 Projects",
      collapsed: true,
      items: [
        "projects/project1_2023",
        "projects/project2_2023",
        "projects/project3_2023",
      ],
    },
    // // UNCOMMENT TO SEE TUTORIALS + TIPS
    // {
    //   type: 'category',
    //   label: 'Tutorial Basics',
    //   items: [
    //     'tutorial-basics/congratulations',
    //     'tutorial-basics/create-a-blog-post',
    //     'tutorial-basics/create-a-document',
    //     'tutorial-basics/create-a-page',
    //     'tutorial-basics/deploy-your-site',
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Tutorial Extras',
    //   items: [
    //     'tutorial-extras/manage-docs-versions',
    //     'tutorial-extras/translate-your-site',
    //     'tutorial-extras/intro',
    //   ],
    // },
  ],
};

export default sidebars;
