import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  projectSidebar: [
    {
      type: "category",
      label: "Bikes",
      collapsed: true,
      items: [
        "bikes/f2025-ebike",
        "bikes/f2025-mid-bike-conversion-kit",
        "bikes/w2025-bakfiets",
        "bikes/w2025-road-bike",
        "bikes/w2025-longtail-conversion-kit",
        "bikes/f2023-quickmefs",
        "bikes/f2023-bmer",
        "bikes/s2023-volter",
      ],
    },
    {
      type: "category",
      label: "Skateboards",
      collapsed: true,
      items: [
        "skateboards/f2025-skateboard",
        "skateboards/w2025-electric-skateboard",
        "skateboards/s2024-maelyns-skateboard",
        "skateboards/s2023-georges-skateboard",
      ],
    },
    {
      type: "category",
      label: "Onewheels",
      collapsed: true,
      items: [
        "onewheels/w2025-onewheel",
        "onewheels/w2024-onewheel",
        "onewheels/s2023-wonwheel",
      ],
    },
    {
      type: "category",
      label: "Other Vehicles",
      collapsed: true,
      items: [
        "other-vehicles/w2025-gokart",
        "other-vehicles/w2025-scooter",
        "other-vehicles/w2025-electric-couch",
      ],
    },
    {
      type: "category",
      label: "Hardware",
      collapsed: true,
      items: [
        "hardware/f2025-portable-media-player",
        "hardware/w2025-custom-remote-control",
      ],
    },
    {
      type: "category",
      label: "Software",
      collapsed: true,
      items: [
        "software/f2025-electrium-shop",
        "software/f2025-auto-pr-reviewer",
        "software/f2025-meeting-note-generator",
        "software/f2025-request-platform",
        "software/f2025-smart-qa-bot",
        "software/w2025-electrium-shop",
      ],
    },
    // // UNCOMMENT TO SEE TUTORIALS + TIPS
    // {
    //   type: 'category',
    //   label: 'Tutorial Basics',
    //   items: [
    //     'tutorial-basics/congratulations',
    //     'tutorial-basics/create-a-blog-post',
    //     'tutorial-basics/create-a-document',
    //     'tutorial-basics/create-a-page',
    //     'tutorial-basics/deploy-your-site',
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Tutorial Extras',
    //   items: [
    //     'tutorial-extras/manage-docs-versions',
    //     'tutorial-extras/translate-your-site',
    //     'tutorial-extras/intro',
    //   ],
    // },
  ],
};

export default sidebars;
