export const SELECT_PROGRAMS = [
  "Accounting and Financial Management",
  "Actuarial Science",
  "Anthropology",
  "Applied Mathematics",
  "Architectural Engineering",
  "Architecture",
  "Bachelor of Arts",
  "Bachelor of Science",
  "Biochemistry",
  "Biological and Medical Physics",
  "Biology",
  "Biomedical Engineering",
  "Biomedical Sciences",
  "Biostatistics",
  "Biotechnology/Chartered Professional Accountancy",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Classical Studies",
  "Climate and Environmental Change",
  "Combinatorics and Optimization",
  "Communication Studies",
  "Computational Mathematics",
  "Computer Engineering",
  "Computer Science",
  "Computer Science/Business Administration",
  "Computing and Financial Management",
  "Data Science",
  "Earth Sciences",
  "Economics",
  "Education",
  "Electrical Engineering",
  "English",
  "Environment and Business",
  "Environment, Resources and Sustainability",
  "Environmental Engineering",
  "Environmental Sciences",
  "Fine Arts",
  "French",
  "Gender and Social Justice",
  "Geography and Aviation",
  "Geography and Environmental Management",
  "Geological Engineering",
  "Geomatics",
  "German",
  "Global Business and Digital Arts",
  "Health Sciences",
  "History",
  "Honours Arts",
  "Honours Arts and Business",
  "Honours Science",
  "Information Technology Management",
  "Kinesiology",
  "Knowledge Integration",
  "Legal Studies",
  "Liberal Studies",
  "Life Sciences",
  "Management Engineering",
  "Materials and Nanosciences",
  "Mathematical Economics",
  "Mathematical Finance",
  "Mathematical Optimization",
  "Mathematical Physics",
  "Mathematics",
  "Mathematics/Business Administration",
  "Mathematics/Chartered Professional Accountancy",
  "Mathematics/Financial Analysis and Risk Management",
  "Mathematics/Teaching",
  "Mechanical Engineering",
  "Mechatronics Engineering",
  "Medicinal Chemistry",
  "Medieval Studies",
  "Music",
  "Nanotechnology Engineering",
  "Nursing",
  "Optometry",
  "Peace and Conflict Studies",
  "Pharmacy",
  "Philosophy",
  "Physics",
  "Planning",
  "Political Science",
  "Psychology",
  "Public Health",
  "Pure Mathematics",
  "Recreation and Leisure Studies",
  "Religious Studies",
  "Science and Business",
  "Science and Aviation",
  "Sexuality, Marriage, and Family Studies",
  "Social Development Studies",
  "Social Work",
  "Software Engineering",
  "Sociology",
  "Spanish",
  "Speech Communication",
  "Statistics",
  "Sustainability and Financial Management",
  "Systems Design Engineering",
  "Theatre and Performance",
  "Theological Studies",
  "Therapeutic Recreation",
  "Urban Planning",
];

export const SELECT_HEARD_SOURCE = [
  "From a friend/word of mouth",
  "Social Media (LinkedIn, Instagram, etc.)",
  "Event (i.e. Fall Open House)",
  "Posters Around Campus",
  "Online (UW Imprint, UW Website, etc.)",
  "Discord",
  "Other",
];

export const SELECT_ROLES = [
  "Project Lead",
  "Team Lead",
  "Electrical",
  "Finance",
  "Firmware",
  "Management",
  "Marketing",
  "Mechanical",
  "Web Development",
];

export const SELECT_PROJECTS = [
  "Electric Bike",
  "Electric Skateboard",
  "e-Human Powered Vehicle",
  "Crowdsourced PEV Charging Map",
  "Web Dev General Project",
  "Other",
];

export const SELECT_TERMS = ["1A", "1B", "2A", "2B", "3A", "3B", "4A", "4B"];
export const SELECT_STREAMS = ["Stream 4", "Stream 8", "Others"];
